service: elasticsearch-golang-3

provider:
    name: aws
    region: eu-central-1
    runtime: go1.x

custom:
    TODO_TABLE: ${self:service}-todo-table

plugins:
    - serverless-go-plugin
    - serverless-iam-roles-per-function


functions:
    dbstream:
        iamRoleStatementsName: ${self:service}-dbstream-lambda
        iamRoleStatements:
            - Effect: Allow
              Action:
                  - dynamodb:ListStreams
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
              Resource:
                  - !GetAtt [TodoTable, "Arn"]
        handler: ./functions/dbstream
        events:
            - stream:
                  type: dynamodb
                  batchSize: 1
                  enabled: true
                  arn: !GetAtt [TodoTable, "StreamArn"]
    graphql:
        iamRoleStatementsName: ${self:service}-graphql-lambda
        iamRoleStatements:
            - Effect: Allow
              Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
              Resource:
                  - !GetAtt [TodoTable, "Arn"]
                  - !Join ["", [!GetAtt [TodoTable, "Arn"], "/*"]]
        environment:
            TODO_TABLE: ${self:custom.TODO_TABLE}
        handler: ./functions/graphql
        package:
            include:
                - ./schema.graphql
        events:
            - http:
                  path: graphql
                  method: POST


resources:
    - ${file(resources/dynamo.yml)}