// Code generated by MockGen. DO NOT EDIT.
// Source: elastic-search/pkg/todo (interfaces: StoreIface)

// Package mock is a generated GoMock package.
package mock

import (
	todo "elastic-search/pkg/todo"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStoreIface is a mock of StoreIface interface
type MockStoreIface struct {
	ctrl     *gomock.Controller
	recorder *MockStoreIfaceMockRecorder
}

// MockStoreIfaceMockRecorder is the mock recorder for MockStoreIface
type MockStoreIfaceMockRecorder struct {
	mock *MockStoreIface
}

// NewMockStoreIface creates a new mock instance
func NewMockStoreIface(ctrl *gomock.Controller) *MockStoreIface {
	mock := &MockStoreIface{ctrl: ctrl}
	mock.recorder = &MockStoreIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStoreIface) EXPECT() *MockStoreIfaceMockRecorder {
	return m.recorder
}

// GetByID mocks base method
func (m *MockStoreIface) GetByID(arg0 string) (todo.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0)
	ret0, _ := ret[0].(todo.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockStoreIfaceMockRecorder) GetByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStoreIface)(nil).GetByID), arg0)
}

// Save mocks base method
func (m *MockStoreIface) Save(arg0 todo.Todo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockStoreIfaceMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStoreIface)(nil).Save), arg0)
}
